# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
